version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shop_sphere_backend_jenkins
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://yashfa:<yashfadb>@cluster0.63xwdrn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./server:/app
    networks:
      - shop-sphere-ci-network

  frontend:
    build:
      context: ./my-project
      dockerfile: Dockerfile
    container_name: shop_sphere_frontend_jenkins
    ports:
      - "5100:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - server
    networks:
      - shop-sphere-ci-network

networks:
  shop-sphere-ci-network:
    driver: bridge

